/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sample_change_me_clothesdetect_nativeMothed_NativeMothed */

#ifndef _Included_sample_change_me_clothesdetect_nativeMothed_NativeMothed
#define _Included_sample_change_me_clothesdetect_nativeMothed_NativeMothed
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sample_change_me_clothesdetect_nativeMothed_NativeMothed
 * Method:    nativeSetBaseImage
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_sample_change_me_clothesdetect_nativeMothed_NativeMothed_nativeSetBaseImage
  (JNIEnv *, jclass, jobject);

/*
 * Class:     sample_change_me_clothesdetect_nativeMothed_NativeMothed
 * Method:    nativeGetImage
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_sample_change_me_clothesdetect_nativeMothed_NativeMothed_nativeGetImage
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
